services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.${DOCKER_BASE_IMAGE:-distroless}
    ports:
      - "${APP_PORT:-8000}:8000"
      - "8443:8443"
    environment:
      - APP_PORT=${APP_PORT:-8000}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_TIMEZONE=${DB_TIMEZONE}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis

  db:
    image: postgres:${DOCKER_POSTGRES_VERSION:-18-alpine}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${DB_TIMEZONE}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:${DOCKER_REDIS_VERSION:-8-alpine}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/jaeger:${DOCKER_JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug

  prometheus:
    image: prom/prometheus:${DOCKER_PROMETHEUS_VERSION:-latest}
    ports:
      - "9090:9090"

volumes:
  db_data:
  redis_data: